---
abstract: 'interface to snapshot.debian.org'
author:
  - 'Ansgar Burchardt <ansgar@43-1.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Debian-Snapshot
recommends: {}
requires:
  File::Spec: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Params::Validate: 0
  MooseX::StrictConstructor: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/aburch/Debian-Snapshot.git
version: 0.002
